name: Build Flutter Web App

on:
  workflow_dispatch:


jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.x' # Specify the Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web/
